<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ext"
 *
 * Auto generated by famelo/soup 2015-12-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Backend Module for Categories',
  'description' => '',
  'category' => 'module',
  'author' => 'Marc neuhaus',
  'author_email' => 'marc@mia3.com',
  'state' => 'alpha',
  'internal' => '',
  'uploadfolder' => '1',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.0',
  'constraints' => 
  array (
    'depends' => 
    array (
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
);